[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "typeclass"
version = "0.1.0"
requires-python = ">=3.13"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
